function [fitresult, gof] = createFit(Years, Keff)
%CREATEFIT(YEARS,KEFF)
%  Create a fit.
%
%  Data for 'Multiplication Constant Estimate' fit:
%      X Input : Years
%      Y Output: Keff
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 11-Mar-2023 18:38:41


%% Fit: 'Multiplication Constant Estimate'.
[xData, yData] = prepareCurveData( Years, Keff );

% Set up fittype and options.
ft = fittype( 'exp2' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.StartPoint = [1.12452015939298 -0.000493578792867439 -0.119465399299258 -0.00645829083770484];

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% Plot fit with data.
figure( 'Name', 'Multiplication Constant Estimate' );
h = plot( fitresult, xData, yData );
legend( h, 'Keff vs. Years', 'Multiplication Constant Estimate', 'Location', 'NorthEast' );
% Label axes
xlabel Years
ylabel Keff
grid on


